version: "3.8"

services:

  influxdb:
    image: influxdb:1.8
    volumes:
      - /home/user/data/influxdb-data:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=M13

  grafana:
    image: grafana/grafana
    user: "0"
    volumes:
      - /home/user/data/grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
